services:
  cli-agent-dogukangundogan:
    build:
      context: ../..
      dockerfile: ./agent/general/Dockerfile
    container_name: jarvis-cli-dogukangundogan-1762603988
    ports:
      - "9988:8080"
    environment:
      - OPENAI_API_KEY=sk-proj-n38C0NhfJXn2geVhKorpdHHzVXDhrkH0YaYeJ_N37umP5eQN04fk9N1BNCzmODXTiUyz4rJQsbT3BlbkFJs2imEoKITbQF_uyof9SLPD_XcKIDvdA6
      - AGENT_MODE=http
      - USER_ID=dogukangundogan
      - CONTAINER_NAME=jarvis-cli-dogukangundogan-1762603988
    networks:
      - jarvis-network
    restart: unless-stopped
